### ISSUE TITLE
labelling files

### ISSUE THREAD

**Issue by Armand1** [smarsland/pots#4] opened 2019-08-06 19:50 UTC
Can we get all files labelled in a standard way? Something like

idnumber_shape_datatype.csv

There's quite a bit of variation, which I have to sort out using regex to get the shapes and ids from the file names.

**Comment by LittleAri** [comment] 2019-08-07 11:50
Sure! Would something like the following work:

11273_little-master-lip-cup_original.csv
11273_little-master-lip-cup_registered.csv
11273_little-master-lip-cup_plot.png

**Comment by Armand1** [comment] 2019-08-07 12:23
Super. That's basically what you did, but there was sufficient variation that it needed cleaning up, some manual.

**Comment by LittleAri** [comment] 2019-08-13 02:27
Hiya! Not sure if you've seen the new names on Dropbox but I wrote some code to change the names. There was a lot of inconsistency in the names caused by different things e.g. there were some cups that had "bell" in their name since their contour had been extracted using the bell krater extraction code and I had probably labelled them with "bell" at some point to distinguish them for that reason. Others had no classes at all and just their IDs, perhaps due to regex mishaps. So yes,  there were a lot of edits. I'm glad it's looking neater now! 

So I've labelled them all ID_class_datatype as you suggested. There are just two things to note:
1) For some pots, I wasn't sure how accurate their ID was so they've been labelled like the following, for example, 26_amphora-no-id_registered.csv. This is so I can distinguish them and thus I'll easily be able to change them once their ID is verified. 
2) For the optimal reparametrisations found from the registering the contours, I've shortened the CSVs to just say ID_class_reparam.csv. 

`
```
import os 
import re
direc_nme = 'C:\\Users\\arian\\Dropbox\\Pot_Registration_Test\\Registered_contours_CSVs' # Folder with files to be renamed.

for filename in os.listdir(direc_nme): 
    if  filename.endswith(".csv"): # change depending on file extension of file you are renaming.
        
        A = re.search('\w+',filename).group(0)
        B = re.search('\d+',A).group(0) # Gets pot ID.
        
        for subdir, dirs, files in os.walk('C:\\Users\\arian\\Dropbox\\selected vase classes'):
            if "number"+B+"." in str(files) or "_"+B+"_" in str(files):
                C = re.search('([a-z]| |_)+$',str(subdir)).group(0) # Shall use the folder name to class pot.
                
        C_ = C.replace(" ","-") #Some classes with multiple names have spaces in the folder name
        C_ = C_.replace("_","-") # whilst others have underscores. We'll change them all to have dashes instead.
        
        nme = B+"_"+C_+"_registered.csv"
        os.rename(direc_nme+'\\'+filename,direc_nme+'\\'+nme)
```

If there are any changes you would like to make feel free to let me know. Alternatively, you can try changing the names using the Python code above (it's super easy now == less manual work - yay(!)). Else, we can close the issue once everyone is happy. 👍

**Comment by Armand1** [comment] 2019-08-13 13:42
great thanks

**Comment by LittleAri** [comment] 2020-01-28 01:35
A very minor detail but as I'm about to run some contour extraction on 8,000 or so pots and will be updating filenames in the process, I thought I'd temporarily re-open this issue and ask everyone about their preferences on filenames. 

Is everyone happy with the following:
place-style-class-id e.g. athenian_protogeometric_pyxis_1008938.png
or perhaps class-place-style-id is more preferable .e.g  pyxis_athenian_protogeometric_1008938.png ? Or other suggestions are welcome too!

Thought I'd ask just in case anyone had any strong preferences. :)

**Comment by Armand1** [comment] 2020-01-28 08:28
Place-style-class pref. I think.

Best
A

Sent from my iPhone

On 28 Jan 2020, at 01:35, Arianna <notifications@github.com> wrote:

﻿
This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



A very minor detail but as I'm about to run some contour extraction on 8,000 or so pots and will be updating filenames in the process, I thought I'd temporarily re-open this issue and ask everyone about their preferences on filenames.

Is everyone happy with the following:
place-style-class-id e.g. athenian_protogeometric_pyxis_1008938.png
or perhaps class-place-style-id is more preferable .e.g pyxis_athenian_protogeometric_1008938.png ? Or other suggestions are welcome too!

Thought I'd ask just in case anyone had any strong preferences. :)

**Comment by LittleAri** [comment] 2020-01-28 13:54
Perfect!

**Closed as completed** 2020-01-28 13:55 UTC
